pipeline {
    agent any
    triggers {
        cron('H */8 * * *')
        pollSCM('* * * * *')
    }
    stages {
        stage('Clone the Git') {
            steps {
                git branch: 'module6', credentialsId: '*****', url: 'https://github.com/denissak/MJC.git'
            }
        }
        stage('Build project') {
            steps {
                    bat './gradlew api:clean api:build'
            }
        }
        stage('Deploy project') {
            steps {
                deploy adapters: [tomcat9(credentialsId: '*****',
                        path: '', url: 'http://localhost:8090')], contextPath: 'mjc', war: '**/*.war'
            }
        }
    }
}
